[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20
via_ir = true

[profile.default.fmt]
line_length = 120

[rpc_endpoints]
og = "https://evmrpc-testnet.0g.ai"
adi = "https://rpc.ab.testnet.adifoundation.ai/"
local = "http://127.0.0.1:8545"
